### PR TITLE
Themes fixes

### PR DESCRIPTION
**Pull request by anion155**

### CODE REVIEW

**Comment by Sadi58** [comment]
Thanks...

**Comment by Sadi58** [comment]
How about you forking this (virtually abandoned) small project to carry it forward?

**Comment by anion155** [comment]
Well I made some changes already in my fork, but they are more cosmetic then useful, like delete intel.png and amd.png and replace them for links. I'll continue maintain fork, until my notebook with me.

**Comment by Sadi58** [comment]
Good idea. I don't have that notebook any longer, so I think I should better Unwatch this project from now on ;-)

**Pull request merged**
